# Generated by Django 5.0.9 on 2026-08-26 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bedesk', '0007_sala_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('ESPORTIVO', 'Esportivo'), ('ACADEMICO', 'Acadêmico'), ('INSTITUCIONAL', 'Institucional'), ('OUTRO', 'Outro')], default='OUTRO', max_length=15)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de término')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de término')),
                ('vagas', models.PositiveIntegerField(blank=True, help_text='Deixe vazio para inscrições ilimitadas.', null=True)),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamentos', models.ManyToManyField(blank=True, related_name='eventos', to='bedesk.agendamento')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='bedesk.sala', verbose_name='Espaço utilizado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_evento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status'], name='eventos_eve_status_df7d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_inicio'], name='eventos_eve_data_in_3661d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoevento',
            constraint=models.UniqueConstraint(fields=('evento', 'usuario'), name='inscricao_unica_por_evento'),
        ),
    ]
