# Generated by Django 5.2.7 on 2026-09-30 23:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bedesk', '0007_sala_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito bom'), (5, '5 - Excelente')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota geral')),
                ('limpeza', models.PositiveSmallIntegerField(choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito bom'), (5, '5 - Excelente')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Limpeza')),
                ('estrutura', models.PositiveSmallIntegerField(choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito bom'), (5, '5 - Excelente')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Estrutura')),
                ('organizacao', models.PositiveSmallIntegerField(choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito bom'), (5, '5 - Excelente')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Organização')),
                ('conservacao', models.PositiveSmallIntegerField(choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito bom'), (5, '5 - Excelente')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Conservação')),
                ('comentario', models.TextField(blank=True, help_text='Opcional. Conte o que estava bom ou o que precisa melhorar.', verbose_name='Comentário')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='bedesk.agendamento', verbose_name='Reserva avaliada')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
