# Generated by Django 5.2.7 on 2026-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('RESERVA_CRIADA', 'Reserva criada'), ('RESERVA_APROVADA', 'Reserva aprovada'), ('RESERVA_REJEITADA', 'Reserva rejeitada'), ('RESERVA_CANCELADA', 'Reserva cancelada'), ('EVENTO_CRIADO', 'Novo evento'), ('EVENTO_ATUALIZADO', 'Evento atualizado'), ('EVENTO_CANCELADO', 'Evento cancelado'), ('LEMBRETE', 'Lembrete'), ('ADMIN_NOVA_SOLICITACAO', 'Nova solicitação'), ('CONFLITO_HORARIO', 'Conflito de horário'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=30),
        ),
    ]
