# Generated by Django 5.0.9 on 2026-08-24 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bedesk', '0007_sala_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outro_local', models.CharField(blank=True, help_text='Preencha apenas se o espaço não estiver na lista acima.', max_length=120, verbose_name='Outro espaço')),
                ('categoria', models.CharField(choices=[('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('ESTRUTURAL', 'Estrutural'), ('EQUIPAMENTO', 'Equipamento'), ('ILUMINACAO', 'Iluminação'), ('LIMPEZA', 'Limpeza'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Categoria do problema')),
                ('descricao', models.TextField(help_text='Explique o que está acontecendo e onde exatamente.', verbose_name='Descrição do problema')),
                ('imagem', models.ImageField(blank=True, help_text='Opcional, mas ajuda muito na avaliação.', null=True, upload_to='manutencao/', verbose_name='Foto do problema')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('EM_MANUTENCAO', 'Em manutenção'), ('RESOLVIDA', 'Resolvida')], default='ABERTA', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_manutencao', to='bedesk.sala', verbose_name='Espaço')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_manutencao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de manutenção',
                'verbose_name_plural': 'Solicitações de manutenção',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('EM_MANUTENCAO', 'Em manutenção'), ('RESOLVIDA', 'Resolvida')], max_length=15)),
                ('status_novo', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('EM_MANUTENCAO', 'Em manutenção'), ('RESOLVIDA', 'Resolvida')], max_length=15)),
                ('observacao', models.TextField(blank=True, help_text='O que foi verificado ou resolvido.', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_manutencao', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='manutencao.solicitacaomanutencao')),
            ],
            options={
                'verbose_name': 'Registro de manutenção',
                'verbose_name_plural': 'Histórico de manutenção',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacaomanutencao',
            index=models.Index(fields=['status'], name='manutencao__status_797c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaomanutencao',
            index=models.Index(fields=['prioridade'], name='manutencao__priorid_fc6eb1_idx'),
        ),
    ]
