# Generated by Django 5.2.7 on 2026-09-16 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bedesk', '0007_sala_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira')], verbose_name='Dia da semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de término')),
                ('descricao', models.CharField(help_text='Ex.: Treino de futsal da equipe do campus', max_length=150, verbose_name='O que ocupa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_fixos_criados', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_fixos', to='bedesk.sala', verbose_name='Espaço')),
            ],
            options={
                'verbose_name': 'Horário fixo',
                'verbose_name_plural': 'Horários fixos',
                'ordering': ['sala__nome', 'dia_semana', 'horario_inicio'],
                'indexes': [models.Index(fields=['sala', 'dia_semana'], name='reservas_ho_sala_id_50421e_idx')],
                'constraints': [models.UniqueConstraint(fields=('sala', 'dia_semana', 'horario_inicio'), name='horario_fixo_unico_por_sala_dia_e_inicio')],
            },
        ),
    ]
